/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service
 * © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 3.0.3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sbi

import (
	"net/http"
	"strconv"
	"strings"

	"github.com/gin-gonic/gin"

	"github.com/free5gc/chf/internal/logger"
	"github.com/free5gc/openapi"
	"github.com/free5gc/openapi/models"
	"github.com/free5gc/util/metrics/sbi"
)

func (s *Server) getConvergenChargingRoutes() []Route {
	return []Route{
		{
			Method:  http.MethodGet,
			Pattern: "/",
			APIFunc: func(c *gin.Context) {
				c.String(http.StatusOK, "Hello free5GC!")
			},
		},
		{
			Method:  http.MethodPost,
			Pattern: "/chargingdata/:ChargingDataRef/release",
			APIFunc: s.ChargingdataChargingDataRefReleasePost,
		},
		{
			Method:  http.MethodPost,
			Pattern: "/chargingdata/:ChargingDataRef/update",
			APIFunc: s.ChargingdataChargingDataRefUpdatePost,
		},
		{
			Method:  http.MethodPost,
			Pattern: "/chargingdata",
			APIFunc: s.ChargingdataPost,
		},
		{
			Method:  http.MethodGet,
			Pattern: "/recharging",
			APIFunc: s.RechargeGet,
		},
		{
			Method:  http.MethodPut,
			Pattern: "/recharging/:rechargingInfo",
			APIFunc: s.RechargePut,
		},
	}
}

// ChargingdataChargingDataRefReleasePost -
func (s *Server) ChargingdataChargingDataRefReleasePost(c *gin.Context) {
	var chargingDataReq models.ChfConvergedChargingChargingDataRequest

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := models.ProblemDetails{
			Title:  "System failure",
			Status: http.StatusInternalServerError,
			Detail: err.Error(),
			Cause:  "SYSTEM_FAILURE",
		}
		logger.ChargingdataPostLog.Errorf("Get Request Body error: %+v", err)
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, problemDetail.Cause)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Deserialize(&chargingDataReq, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.ChargingdataPostLog.Errorln(problemDetail)
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, http.StatusText(http.StatusBadRequest))
		c.JSON(http.StatusBadRequest, rsp)
		return
	}
	chargingSessionId := c.Param("ChargingDataRef")

	s.Processor().HandleChargingdataRelease(c, chargingDataReq, chargingSessionId)
}

// ChargingdataChargingDataRefUpdatePost
func (s *Server) ChargingdataChargingDataRefUpdatePost(c *gin.Context) {
	var chargingDataReq models.ChfConvergedChargingChargingDataRequest

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := models.ProblemDetails{
			Title:  "System failure",
			Status: http.StatusInternalServerError,
			Detail: err.Error(),
			Cause:  "SYSTEM_FAILURE",
		}
		logger.ChargingdataPostLog.Errorf("Get Request Body error: %+v", err)
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, problemDetail.Cause)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Deserialize(&chargingDataReq, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.ChargingdataPostLog.Errorln(problemDetail)
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, http.StatusText(http.StatusBadRequest))
		c.JSON(http.StatusBadRequest, rsp)
		return
	}
	chargingSessionId := c.Param("ChargingDataRef")

	s.Processor().HandleChargingdataUpdate(c, chargingDataReq, chargingSessionId)
}

// ChargingdataPost
func (s *Server) ChargingdataPost(c *gin.Context) {
	var chargingDataReq models.ChfConvergedChargingChargingDataRequest

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := models.ProblemDetails{
			Title:  "System failure",
			Status: http.StatusInternalServerError,
			Detail: err.Error(),
			Cause:  "SYSTEM_FAILURE",
		}
		logger.ChargingdataPostLog.Errorf("Get Request Body error: %+v", err)
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, problemDetail.Cause)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Deserialize(&chargingDataReq, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := models.ProblemDetails{
			Title:  "Malformed request syntax",
			Status: http.StatusBadRequest,
			Detail: problemDetail,
		}
		logger.ChargingdataPostLog.Errorln(problemDetail)
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, http.StatusText(http.StatusBadRequest))
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	s.Processor().HandleChargingdataInitial(c, chargingDataReq)
}

func (s *Server) RechargeGet(c *gin.Context) {
	c.String(http.StatusOK, "recharge")
}

func (s *Server) RechargePut(c *gin.Context) {
	rechargingInfo := c.Param("rechargingInfo")
	ueIdRatingGroup := strings.Split(rechargingInfo, "_")

	if len(ueIdRatingGroup) < 2 {
		problemDetail := models.ProblemDetails{
			Title:  "Invalid rechargingInfo format",
			Status: http.StatusBadRequest,
			Detail: "rechargingInfo must be in format: {ueId}_{ratingGroup}",
		}
		logger.RechargingLog.Errorf("Invalid rechargingInfo format: %s", rechargingInfo)
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, http.StatusText(http.StatusBadRequest))
		c.JSON(http.StatusBadRequest, problemDetail)
		return
	}

	ueId := ueIdRatingGroup[0]
	rgStr := ueIdRatingGroup[1]
	rg, err := strconv.Atoi(rgStr)
	if err != nil {
		problemDetail := models.ProblemDetails{
			Title:  "Invalid ratingGroup",
			Status: http.StatusBadRequest,
			Detail: "ratingGroup must be a valid integer",
		}
		logger.RechargingLog.Errorf("UE[%s] invalid ratingGroup: %s", ueId, rgStr)
		c.Set(sbi.IN_PB_DETAILS_CTX_STR, http.StatusText(http.StatusBadRequest))
		c.JSON(http.StatusBadRequest, problemDetail)
		return
	}

	logger.RechargingLog.Warnf("UE[%s] Recharge for rating group %d", ueId, rg)

	s.Processor().NotifyRecharge(ueId, int32(rg))

	c.Status(http.StatusNoContent)
}
