// /*
//  * Nchf_ConvergedCharging
//  *
//  * ConvergedCharging Service    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
//  *
//  * API version: 3.0.3
//  * Generated by: OpenAPI Generator (https://openapi-generator.tech)
//  */

package convergedcharging

// import (
// 	"net/http"

// 	"github.com/free5gc/chf/internal/logger"
// 	"github.com/free5gc/chf/internal/sbi/producer"
// 	"github.com/free5gc/openapi"
// 	"github.com/free5gc/openapi/models"
// 	"github.com/free5gc/util/httpwrapper"
// 	"github.com/gin-gonic/gin"
// )

// // ChargingdataChargingDataRefReleasePost -
// func ChargingdataChargingDataRefReleasePost(c *gin.Context) {
// 	var chargingDataReq models.ChargingDataRequest

// 	requestBody, err := c.GetRawData()
// 	if err != nil {
// 		problemDetail := models.ProblemDetails{
// 			Title:  "System failure",
// 			Status: http.StatusInternalServerError,
// 			Detail: err.Error(),
// 			Cause:  "SYSTEM_FAILURE",
// 		}
// 		logger.ChargingdataPostLog.Errorf("Get Request Body error: %+v", err)
// 		c.JSON(http.StatusInternalServerError, problemDetail)
// 		return
// 	}

// 	err = openapi.Deserialize(&chargingDataReq, requestBody, "application/json")
// 	if err != nil {
// 		problemDetail := "[Request Body] " + err.Error()
// 		rsp := models.ProblemDetails{
// 			Title:  "Malformed request syntax",
// 			Status: http.StatusBadRequest,
// 			Detail: problemDetail,
// 		}
// 		logger.ChargingdataPostLog.Errorln(problemDetail)
// 		c.JSON(http.StatusBadRequest, rsp)
// 		return
// 	}

// 	req := httpwrapper.NewRequest(c.Request, chargingDataReq)
// 	req.Params["ChargingDataRef"] = c.Param("ChargingDataRef")

// 	rsp := producer.HandleChargingdataRelease(req)

// 	for key, value := range rsp.Header {
// 		c.Header(key, value[0])
// 	}
// 	responseBody, err := openapi.Serialize(rsp.Body, "application/json")
// 	if err != nil {
// 		logger.ChargingdataPostLog.Errorln(err)
// 		problemDetails := models.ProblemDetails{
// 			Status: http.StatusInternalServerError,
// 			Cause:  "SYSTEM_FAILURE",
// 			Detail: err.Error(),
// 		}
// 		c.JSON(http.StatusInternalServerError, problemDetails)
// 	} else {
// 		c.Data(rsp.Status, "application/json", responseBody)
// 	}
// }

// // ChargingdataChargingDataRefUpdatePost -
// func ChargingdataChargingDataRefUpdatePost(c *gin.Context) {
// 	var chargingDataReq models.ChargingDataRequest

// 	requestBody, err := c.GetRawData()
// 	if err != nil {
// 		problemDetail := models.ProblemDetails{
// 			Title:  "System failure",
// 			Status: http.StatusInternalServerError,
// 			Detail: err.Error(),
// 			Cause:  "SYSTEM_FAILURE",
// 		}
// 		logger.ChargingdataPostLog.Errorf("Get Request Body error: %+v", err)
// 		c.JSON(http.StatusInternalServerError, problemDetail)
// 		return
// 	}

// 	err = openapi.Deserialize(&chargingDataReq, requestBody, "application/json")
// 	if err != nil {
// 		problemDetail := "[Request Body] " + err.Error()
// 		rsp := models.ProblemDetails{
// 			Title:  "Malformed request syntax",
// 			Status: http.StatusBadRequest,
// 			Detail: problemDetail,
// 		}
// 		logger.ChargingdataPostLog.Errorln(problemDetail)
// 		c.JSON(http.StatusBadRequest, rsp)
// 		return
// 	}

// 	req := httpwrapper.NewRequest(c.Request, chargingDataReq)
// 	req.Params["ChargingDataRef"] = c.Param("ChargingDataRef")

// 	rsp := producer.HandleChargingdataUpdate(req)

// 	for key, value := range rsp.Header {
// 		c.Header(key, value[0])
// 	}
// 	responseBody, err := openapi.Serialize(rsp.Body, "application/json")
// 	if err != nil {
// 		logger.ChargingdataPostLog.Errorln(err)
// 		problemDetails := models.ProblemDetails{
// 			Status: http.StatusInternalServerError,
// 			Cause:  "SYSTEM_FAILURE",
// 			Detail: err.Error(),
// 		}
// 		c.JSON(http.StatusInternalServerError, problemDetails)
// 	} else {
// 		c.Data(rsp.Status, "application/json", responseBody)
// 	}
// }

// // ChargingdataPost -
// func ChargingdataPost(c *gin.Context) {
// 	var chargingDataReq models.ChargingDataRequest

// 	requestBody, err := c.GetRawData()
// 	if err != nil {
// 		problemDetail := models.ProblemDetails{
// 			Title:  "System failure",
// 			Status: http.StatusInternalServerError,
// 			Detail: err.Error(),
// 			Cause:  "SYSTEM_FAILURE",
// 		}
// 		logger.ChargingdataPostLog.Errorf("Get Request Body error: %+v", err)
// 		c.JSON(http.StatusInternalServerError, problemDetail)
// 		return
// 	}

// 	err = openapi.Deserialize(&chargingDataReq, requestBody, "application/json")
// 	if err != nil {
// 		problemDetail := "[Request Body] " + err.Error()
// 		rsp := models.ProblemDetails{
// 			Title:  "Malformed request syntax",
// 			Status: http.StatusBadRequest,
// 			Detail: problemDetail,
// 		}
// 		logger.ChargingdataPostLog.Errorln(problemDetail)
// 		c.JSON(http.StatusBadRequest, rsp)
// 		return
// 	}

// 	req := httpwrapper.NewRequest(c.Request, chargingDataReq)

// 	rsp := producer.HandleChargingdataInitial(req)

// 	for key, value := range rsp.Header {
// 		c.Header(key, value[0])
// 	}
// 	responseBody, err := openapi.Serialize(rsp.Body, "application/json")
// 	if err != nil {
// 		logger.ChargingdataPostLog.Errorln(err)
// 		problemDetails := models.ProblemDetails{
// 			Status: http.StatusInternalServerError,
// 			Cause:  "SYSTEM_FAILURE",
// 			Detail: err.Error(),
// 		}
// 		c.JSON(http.StatusInternalServerError, problemDetails)
// 	} else {
// 		c.Data(rsp.Status, "application/json", responseBody)
// 	}
// }
